SitePoint.roots.each(&:destroy)

home = SitePoint.create(name: 'Home', path: nil)
  settings = SitePoint.create(name: 'Settings', path: 'settings', parent: home)
    company_profile = SitePoint.create(name: 'Company Profile', path: 'company_profile', parent: settings)
    switches = SitePoint.create(name: 'Switches', path: 'switches', parent: settings)
  help_p = SitePoint.create(name: 'Help', path: 'help', parent: home)
    tickets = SitePoint.create(name: 'Tickets', path: 'tickets', parent: help_p)
      create_ticket = SitePoint.create(name: 'Create A Ticket ', path: 'create', parent: tickets)
    faq = SitePoint.create(name: 'FAQ', path: 'faqs', parent: help_p)
